services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
volumes:
  db_data:
